spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: db-service
          uri: lb://db-service
          predicates:
          - Path=/db-service/**
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
          - Path=/cliente-service/**
        - id: openapi
          uri: lb://api-gateway
          predicates:
          - Path=/v3/api-docs/**
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:

  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
    - url: /db-api-docs
      name: db-service
    - url: /cliente-api-docs
      name: cliente-service

